// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lwxhputpykxnyiiwlvhj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx3eGhwdXRweWt4bnlpaXdsdmhqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI5MzI0MzYsImV4cCI6MjA1ODUwODQzNn0.nY30RqG11_5F7wPYnUHcte4XAtkjEK8QutaXiKjM4LA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);